# generated by datamodel-codegen:
#   filename:  riot_open_api.json
#   timestamp: 2024-10-17T17:34:07+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class AccountDto(BaseModel):
    puuid: str
    gameName: Optional[str] = Field(
        None,
        description="This field may be excluded from the response if the account doesn't have a gameName.",
    )
    tagLine: Optional[str] = Field(
        None,
        description="This field may be excluded from the response if the account doesn't have a tagLine.",
    )


class ActiveShardDto(BaseModel):
    puuid: str
    game: str
    activeShard: str
