# generated by datamodel-codegen:
#   filename:  riot_open_api.json
#   timestamp: 2024-10-17T17:34:07+00:00

from __future__ import annotations

from pydantic import BaseModel


class DeckDto(BaseModel):
    id: str
    name: str
    code: str


class NewDeckDto(BaseModel):
    name: str
    code: str
