# generated by datamodel-codegen:
#   filename:  riot_open_api.json
#   timestamp: 2024-10-17T17:34:07+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Status(BaseModel):
    status_code: Optional[int] = None
    message: Optional[str] = None


class Error(BaseModel):
    status: Optional[Status] = None
