# generated by datamodel-codegen:
#   filename:  riot_open_api.json
#   timestamp: 2024-10-17T17:34:07+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ChampionInfo(BaseModel):
    maxNewPlayerLevel: int
    freeChampionIdsForNewPlayers: List[int]
    freeChampionIds: List[int]
